test_that("PROPERTIES$angular_frequency subclass has correct classes", {
  w <- angular_frequency(10)
  expect_true(inherits(w, "angular_frequency"))
  expect_true(inherits(w, "property"))
  expect_equal(w$value, 10)
})
test_that("PROPERTIES$angular_frequency constants are legit", {
  expect_equal(PROPERTIES$angular_frequency$name, "angular frequency")
  expect_equal(PROPERTIES$angular_frequency$class_name, "angular_frequency")
  expect_equal(PROPERTIES$angular_frequency$unit, "rad/s")
  expect_equal(PROPERTIES$angular_frequency$unit_latex, "\\frac{\\text{rad}}{\\text{s}}")
  expect_equal(PROPERTIES$angular_frequency$symbol, "\u03C9")
  expect_equal(PROPERTIES$angular_frequency$symbol_latex, "\\omega")
  expect_equal(PROPERTIES$angular_frequency$symbol_expression, 'italic(ω)')
  expect_equal(PROPERTIES$angular_frequency$space_time, SPACE_TIME$time)
  expect_equal(PROPERTIES$angular_frequency$linear_angular, LINEAR_ANGULAR$angular)
  expect_equal(PROPERTIES$angular_frequency$rate_extent, RATE_EXTENT$rate)
})
