test_that("linear_wavenumber subclass has correct classes", {
  k_lin <- linear_wavenumber(10)
  expect_true(inherits(k_lin, "linear_wavenumber"))
  expect_true(inherits(k_lin, "property"))
  expect_equal(k_lin$value, 10)
  expect_equal(k_lin$class_name, 'linear_wavenumber')
  expect_equal(k_lin$space_time, SPACE_TIME$space)
  expect_equal(k_lin$linear_angular,  LINEAR_ANGULAR$linear)
  expect_equal(k_lin$extent_rate,   EXTENT_RATE$rate)
  expect_equal(k_lin$unit, "1/m")
  expect_equal(k_lin$unit_latex, "\\text{m}^{-1}")
  expect_equal(k_lin$symbol, "k_linear")
  expect_equal(k_lin$symbol_latex, "k_{\\text{linear}}")
  expect_equal(k_lin$symbol_expression, 'italic(k)["linear"]')
  expect_equal(k_lin$name, "linear wavenumber")
})
