test_that("linear_period subclass has correct classes", {
  P <- linear_period(10)
  expect_true(inherits(P, "linear_period"))
  expect_true(inherits(P, "property"))
  expect_equal(P$class_name, 'linear_period')
  expect_equal(P$value, 10)
  expect_equal(P$name, "linear period")
  expect_equal(P$class_name, 'linear_period')
  expect_equal(P$unit, "s")
  expect_equal(P$unit_latex, "\\text{s}")
  expect_equal(P$unit_expression, "s")
  expect_equal(P$symbol, "T")
  expect_equal(P$symbol_latex, "T")
  expect_equal(P$symbol_expression, "italic(T)")
  expect_equal(P$space_time, SPACE_TIME$time)
  expect_equal(P$linear_angular,  LINEAR_ANGULAR$linear)
  expect_equal(P$extent_rate,   EXTENT_RATE$extent)
})
