test_that("linear_wavelength subclass has correct classes", {
  l <- linear_wavelength(10)
  expect_true(inherits(l, "linear_wavelength"))
  expect_true(inherits(l, "property"))
  expect_equal(l$value, 10)
  expect_equal(l$class_name, 'linear_wavelength')
  expect_equal(l$space_time, TIME_SPACE$space)
  expect_equal(l$linear_angular,  LINEAR_ANGULAR$linear)
  expect_equal(l$rate_extent,   EXTENT_RATE$extent)
  expect_equal(l$unit, "m")
  expect_equal(l$unit_latex, "\\text{m}")
  expect_equal(l$symbol, "\u03BB")
  expect_equal(l$symbol_latex, "\\lambda")
  expect_equal(l$symbol_expression, "italic(λ)")
  expect_equal(l$name, "linear wavelength")
})
