test_that("angular_period subclass has correct classes", {
  T_ang <- angular_period(10)
  expect_true(inherits(T_ang, "angular_period"))
  expect_true(inherits(T_ang, "property"))
  expect_equal(T_ang$value, 10)
  expect_equal(T_ang$name, 'angular period')
  expect_equal(T_ang$class_name, 'angular_period')
  expect_equal(T_ang$unit, "s/rad")
  expect_equal(T_ang$unit_latex, "\\frac{\\text{s}}{\\text{rad}}")
  expect_equal(T_ang$symbol, "T_angular")
  expect_equal(T_ang$symbol_latex, "\\Tau_\\text{angular}")
  expect_equal(T_ang$symbol_expression, 'italic(T)["angular"]')
  expect_equal(T_ang$space_time, SPACE_TIME$time)
  expect_equal(T_ang$linear_angular,  LINEAR_ANGULAR$angular)
  expect_equal(T_ang$extent_rate,   EXTENT_RATE$extent)
})
