test_that("angular_wavelength subclass has correct classes", {
  l_a <- angular_wavelength(10)
  expect_true(inherits(l_a, "angular_wavelength"))
  expect_true(inherits(l_a, "property"))
  expect_equal(l_a$value, 10)
})
test_that("angular_wavelength subclass has correct classes", {
  expect_equal(PROPERTIES$angular_wavelength$name, "angular wavelength")
  expect_equal(PROPERTIES$angular_wavelength$class_name, "angular_wavelength")
  expect_equal(PROPERTIES$angular_wavelength$unit, "m/rad")
  expect_equal(PROPERTIES$angular_wavelength$unit_latex, "\\frac{\\text{m}}{\\text{rad}}")
  expect_equal(PROPERTIES$angular_wavelength$symbol, "l_angular")
  expect_equal(PROPERTIES$angular_wavelength$symbol_latex, "\\lambda_\\text{angular}")
  expect_equal(PROPERTIES$angular_wavelength$symbol_expression, "italic(λ)")
  expect_equal(PROPERTIES$angular_wavelength$space_time, SPACE_TIME$space)
  expect_equal(PROPERTIES$angular_wavelength$linear_angular, LINEAR_ANGULAR$angular)
  expect_equal(PROPERTIES$angular_wavelength$rate_extent, RATE_EXTENT$extent)
})
