test_that("linear_wavenumber subclass has correct classes", {
  l <- linear_wavenumber(10)
  expect_true(inherits(l, "linear_wavenumber"))
  expect_true(inherits(l, "property"))
  expect_equal(l$value, 10)
})
test_that("linear_wavenumber subclass has correct classes", {
  expect_equal(PROPERTIES$linear_wavenumber$class_name, 'linear_wavenumber')
  expect_equal(PROPERTIES$linear_wavenumber$space_time, TIME_SPACE$space)
  expect_equal(PROPERTIES$linear_wavenumber$linear_angular,  LINEAR_ANGULAR$linear)
  expect_equal(PROPERTIES$linear_wavenumber$rate_extent,   EXTENT_RATE$rate)
  expect_equal(PROPERTIES$linear_wavenumber$unit, "1/m")
  expect_equal(PROPERTIES$linear_wavenumber$unit_latex, "\\text{m}^{-1}")
  expect_equal(PROPERTIES$linear_wavenumber$symbol, "k_linear")
  expect_equal(PROPERTIES$linear_wavenumber$symbol_latex, "k_{\\text{linear}}")
  expect_equal(PROPERTIES$linear_wavenumber$symbol_expression, 'italic(k)["linear"]')
  expect_equal(PROPERTIES$linear_wavenumber$name, "linear wavenumber")
})
