test_that("linear_frequency subclass has correct classes", {
  f <- linear_frequency(10)
  expect_true(inherits(f, "linear_frequency"))
  expect_true(inherits(f, "property"))
  expect_equal(f$value, 10)
})
test_that("linear_frequency subclass has correct classes", {
  expect_equal(PROPERTIES$linear_frequency$name, "linear frequency")
  expect_equal(PROPERTIES$linear_frequency$class_name, 'linear_frequency')
  expect_equal(PROPERTIES$linear_frequency$unit, "Hz")
  expect_equal(PROPERTIES$linear_frequency$unit_latex, "\\text{Hz}")
  expect_equal(PROPERTIES$linear_frequency$symbol, "f")
  expect_equal(PROPERTIES$linear_frequency$symbol_latex, "f")
  expect_equal(PROPERTIES$linear_frequency$symbol_expression, "italic(f)")
  expect_equal(PROPERTIES$linear_frequency$space_time, TIME_SPACE$time)
  expect_equal(PROPERTIES$linear_frequency$linear_angular,  LINEAR_ANGULAR$linear)
  expect_equal(PROPERTIES$linear_frequency$rate_extent,   EXTENT_RATE$rate)
})
