test_that("w subclass has correct classes", {
  w <- angular_frequency(10)
  expect_true(inherits(w, "angular_frequency"))
  expect_true(inherits(w, "property"))
  expect_equal(w$value, 10)
  expect_equal(w$name, "angular frequency")
  expect_equal(w$class_name, "angular_frequency")
  expect_equal(w$unit, "rad/s")
  expect_equal(w$unit_latex, "\\frac{\\text{rad}}{\\text{s}}")
  expect_equal(w$symbol, "\u03C9")
  expect_equal(w$symbol_latex, "\\omega")
  expect_equal(w$symbol_expression, 'italic(ω)')
  expect_equal(w$space_time, TIME_SPACE$time)
  expect_equal(w$linear_angular, LINEAR_ANGULAR$angular)
  expect_equal(w$rate_extent, EXTENT_RATE$rate)
})
