test_that("angular_wavenumber subclass has correct classes", {
  k_ang <- angular_wavenumber(10)
  expect_true(inherits(k_ang, "angular_wavenumber"))
  expect_true(inherits(k_ang, "property"))
  expect_equal(k_ang$value, 10)
  expect_equal(k_ang$name, "angular wavenumber")
  expect_equal(k_ang$class_name, "angular_wavenumber")
  expect_equal(k_ang$space_time, SPACE_TIME$space)
  expect_equal(k_ang$linear_angular,  LINEAR_ANGULAR$angular)
  expect_equal(k_ang$extent_rate,   EXTENT_RATE$rate)
  expect_equal(k_ang$unit, "rad/m")
  expect_equal(k_ang$unit_latex, "\\frac{\\text{rad}}{\\text{m}}")
  expect_equal(k_ang$symbol, "k_angular")
  expect_equal(k_ang$symbol_latex, "k_\\text{angular}")
  expect_equal(k_ang$symbol_expression, "italic(k)")
})
