test_that("linear_period subclass has correct classes", {
  P <- linear_period(10)
  expect_true(inherits(P, "linear_period"))
  expect_true(inherits(P, "property"))
  expect_equal(P$class_name, 'linear_period')
  expect_equal(P$value, 10)
})
test_that("linear_period subclass has correct classes", {
  expect_equal(PROPERTIES$linear_period$name, "linear period")
  expect_equal(PROPERTIES$linear_period$class_name, 'linear_period')
  expect_equal(PROPERTIES$linear_period$unit, "s")
  expect_equal(PROPERTIES$linear_period$unit_latex, "\\text{s}")
  expect_equal(PROPERTIES$linear_period$symbol, "T")
  expect_equal(PROPERTIES$linear_period$symbol_latex, "T")
  expect_equal(PROPERTIES$linear_period$symbol_expression, "italic(T)")
  expect_equal(PROPERTIES$linear_period$space_time, TIME_SPACE$time)
  expect_equal(PROPERTIES$linear_period$linear_angular,  LINEAR_ANGULAR$linear)
  expect_equal(PROPERTIES$linear_period$rate_extent,   EXTENT_RATE$extent)
})
