# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

approximate_rational_fractions_cpp <- function(x, uncertainty, deviation, metadata = NULL) {
    .Call(`_wavyr_approximate_rational_fractions_cpp`, x, uncertainty, deviation, metadata)
}

combine_spectra_cpp <- function(component, amplitude, tolerance) {
    .Call(`_wavyr_combine_spectra_cpp`, component, amplitude, tolerance)
}

compute_beats_cpp <- function(component, amplitude, extent_rate, tolerance = 1e-6) {
    .Call(`_wavyr_compute_beats_cpp`, component, amplitude, extent_rate, tolerance)
}

shannon_entropy_cpp <- function(bits) {
    .Call(`_wavyr_shannon_entropy_cpp`, bits)
}

hamming_weight_cpp <- function(bits) {
    .Call(`_wavyr_hamming_weight_cpp`, bits)
}

run_length_encoding_cpp <- function(bits) {
    .Call(`_wavyr_run_length_encoding_cpp`, bits)
}

depth_cpp <- function(bits) {
    .Call(`_wavyr_depth_cpp`, bits)
}

as_string_cpp <- function(bits) {
    .Call(`_wavyr_as_string_cpp`, bits)
}

as_integer_cpp <- function(bits) {
    .Call(`_wavyr_as_integer_cpp`, bits)
}

rationalized_spectrum_cpp <- function(source) {
    .Call(`_wavyr_rationalized_spectrum_cpp`, source)
}

sparse_spectrum_sbg_cpp <- function(nrows, ncols, uncertainty) {
    .Call(`_wavyr_sparse_spectrum_sbg_cpp`, nrows, ncols, uncertainty)
}

stern_brocot_for_scalar_cpp <- function(x, uncertainty) {
    .Call(`_wavyr_stern_brocot_for_scalar_cpp`, x, uncertainty)
}

stern_brocot_for_ratio_cpp <- function(x, y, uncertainty) {
    .Call(`_wavyr_stern_brocot_for_ratio_cpp`, x, y, uncertainty)
}

