# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

approximate_rational_fractions_cpp <- function(x, uncertainty, deviation) {
    .Call(`_wavyr_approximate_rational_fractions_cpp`, x, uncertainty, deviation)
}

combine_spectra_cpp <- function(component, amplitude, tolerance) {
    .Call(`_wavyr_combine_spectra_cpp`, component, amplitude, tolerance)
}

compute_beats_cpp <- function(wavelength, amplitude, tolerance = 1e-6) {
    .Call(`_wavyr_compute_beats_cpp`, wavelength, amplitude, tolerance)
}

stern_brocot_cpp <- function(x, uncertainty) {
    .Call(`_wavyr_stern_brocot_cpp`, x, uncertainty)
}

